### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by wtvtricks** [webtv-redialed/redialed-nodejs#4]
Error: error:0308010C:digital envelope routines::unsupported
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:121:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:140:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:147:10)
    at WTVSec.SecureOn (C:\Users\nope\Downloads\redialed-nodejs-main\redialed-nodejs-main\includes\WTVSec.js:399:45)
    at WTVSec.set_incarnation (C:\Users\nope\Downloads\redialed-nodejs-main\redialed-nodejs-main\includes\WTVSec.js:68:18)
    at C:\Users\nope\Downloads\redialed-nodejs-main\redialed-nodejs-main\ServiceVault\wtv-1800\preregister.js:52:46
    at sigintHandlersWrap (node:vm:279:12)
    at Script.runInContext (node:vm:146:14)
    at Script.runInNewContext (node:vm:153:17) {
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by HIDEN64** [comment]
Run the server with `start.bat`, or this command: `node --openssl-legacy-provider app.js`

**Comment by wtvtricks** [comment]
it send a a TellyScript now it hanging on connecting to webtv

**Comment by HIDEN64** [comment]
Make sure you set "service_ip" in user_config correctly.
If you're usijng an actual WebTV box (which I'm assuming you are), leaving it as default (127.0.0.1) won't work. Set it to whatever your computer's private IP on your network is.

**Comment by HIDEN64** [comment]
Closing due to inactivity.
